version: '3.9'

services:
  db:
    image: postgres:15
    container_name: api_usinas_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: .
    container_name: usinas_api
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./app:/app
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  pgdata:
